// eslint-disable-next-line import/no-anonymous-default-export
export default {
  CLEAR_CURRENT: 'ORDERS_CLEAR_CURRENT',
  GET_REQUEST: 'ORDERS_GET_REQUEST',
  GET_SUCCESS: 'ORDERS_GET_SUCCESS',
  GET_FAILURE: 'ORDERS_GET_FAILURE',

  SAVE_REQUEST: 'ORDERS_SAVER_REQUEST',
  SAVE_SUCCESS: 'ORDERS_SAVE_SUCCESS',
  SAVE_FAILURE: 'ORDERS_SAVE_FAILURE',

  GETALL_REQUEST: 'ORDERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'ORDERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'ORDERS_GETALL_FAILURE',

  DELETE_REQUEST: 'ORDERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'ORDERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'ORDERS_DELETE_FAILURE',    

  UPDATE_REQUEST: 'ORDERS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'ORDERS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'ORDERS_UPDATE_FAILURE'    
};