export default {
  CLEAR_CURRENT: 'VEHICLES_CLEAR_CURRENT',
  GET_REQUEST: 'VEHICLES_GET_REQUEST',
  GET_SUCCESS: 'VEHICLES_GET_SUCCESS',
  GET_FAILURE: 'VEHICLES_GET_FAILURE',

  SAVE_REQUEST: 'VEHICLES_SAVER_REQUEST',
  SAVE_SUCCESS: 'VEHICLES_SAVE_SUCCESS',
  SAVE_FAILURE: 'VEHICLES_SAVE_FAILURE',

  GETALL_REQUEST: 'VEHICLES_GETALL_REQUEST',
  GETALL_SUCCESS: 'VEHICLES_GETALL_SUCCESS',
  GETALL_FAILURE: 'VEHICLES_GETALL_FAILURE',

  DELETE_REQUEST: 'VEHICLES_DELETE_REQUEST',
  DELETE_SUCCESS: 'VEHICLES_DELETE_SUCCESS',
  DELETE_FAILURE: 'VEHICLES_DELETE_FAILURE',    

  UPDATE_REQUEST: 'VEHICLES_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'VEHICLES_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'VEHICLES_UPDATE_FAILURE'    

};