export default {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  FORGOT: 'USERS_LOGIN_FORGOT',
  LOGOUT: 'USERS_LOGOUT',
  LOGGED: 'USERS_LOGGED',

  VERIFY_REQUEST: 'USERS_VERIFY_REQUEST',
  VERIFY_SUCCESS: 'USERS_VERIFY_SUCCESS',
  VERIFY_FAILURE: 'USERS_VERIFY_FAILURE',

  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  CLEAR_CURRENT: 'USERS_CLEAR_CURRENT',
  GET_REQUEST: 'USERS_GET_REQUEST',
  GET_SUCCESS: 'USERS_GET_SUCCESS',
  GET_FAILURE: 'USERS_GET_FAILURE',

  SAVE_REQUEST: 'USERS_SAVE_REQUEST',
  SAVE_SUCCESS: 'USERS_SAVE_SUCCESS',
  SAVE_FAILURE: 'USERS_SAVE_FAILURE',  

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',    

  UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

  GETPOINTS_REQUEST: 'USERS_GETPOINTS_REQUEST',
  GETPOINTS_SUCCESS: 'USERS_GETPOINTS_SUCCESS',
  GETPOINTS_FAILURE: 'USERS_GETPOINTS_FAILURE',

};